--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: faq_admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.faq_admin (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    jawaban text NOT NULL,
    pertanyaan text NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.faq_admin OWNER TO postgres;

--
-- Name: faq_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.faq_admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faq_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kamar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kamar (
    id bigint NOT NULL,
    description text,
    fasilitas text,
    harga_bulan double precision NOT NULL,
    nomor_kamar character varying(255) NOT NULL,
    price double precision NOT NULL,
    status character varying(255) NOT NULL,
    status_pembayaran character varying(255),
    title character varying(255) NOT NULL
);


ALTER TABLE public.kamar OWNER TO postgres;

--
-- Name: kamar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kamar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kamar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kebersihan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kebersihan (
    id bigint NOT NULL,
    area_corridor boolean NOT NULL,
    area_garden boolean NOT NULL,
    area_parking boolean NOT NULL,
    area_terrace boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    notes character varying(255),
    room_number character varying(255),
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.kebersihan OWNER TO postgres;

--
-- Name: kebersihan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kebersihan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kebersihan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.otp_tokens (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    expired_at timestamp(6) without time zone NOT NULL,
    otp character varying(255) NOT NULL
);


ALTER TABLE public.otp_tokens OWNER TO postgres;

--
-- Name: otp_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.otp_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pembayaran; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pembayaran (
    id bigint NOT NULL,
    bulan_bayar character varying(255),
    catatan text,
    created_at timestamp(6) without time zone,
    kamar character varying(255) NOT NULL,
    kamar_id bigint NOT NULL,
    nominal double precision NOT NULL,
    penghuni character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    tahun_bayar integer,
    tanggal_bayar timestamp(6) without time zone,
    tanggal_jatuh_tempo timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint
);


ALTER TABLE public.pembayaran OWNER TO postgres;

--
-- Name: pembayaran_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pembayaran ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pembayaran_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pengumuman; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pengumuman (
    id bigint NOT NULL,
    isi text NOT NULL,
    judul text NOT NULL,
    tanggal_berlaku date NOT NULL
);


ALTER TABLE public.pengumuman OWNER TO postgres;

--
-- Name: pengumuman_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pengumuman ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pengumuman_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: peraturan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.peraturan (
    id bigint NOT NULL,
    deskripsi_peraturan text NOT NULL,
    judul_peraturan text NOT NULL
);


ALTER TABLE public.peraturan OWNER TO postgres;

--
-- Name: peraturan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.peraturan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.peraturan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profile (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255),
    location character varying(255),
    name character varying(255),
    phone character varying(255),
    profile_picture character varying(255),
    room_number integer,
    status character varying(255),
    user_id bigint
);


ALTER TABLE public.profile OWNER TO postgres;

--
-- Name: profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registration (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(255),
    role character varying(255) NOT NULL,
    room_id bigint,
    room_request_status character varying(255),
    username character varying(255) NOT NULL
);


ALTER TABLE public.registration OWNER TO postgres;

--
-- Name: registration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: faq_admin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.faq_admin (id, created_at, jawaban, pertanyaan, updated_at) FROM stdin;
1	2025-10-29 16:31:32.71362	test	test	2025-10-29 16:31:32.71362
\.


--
-- Data for Name: kamar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kamar (id, description, fasilitas, harga_bulan, nomor_kamar, price, status, status_pembayaran, title) FROM stdin;
1	test		12000	001	12000	terisi	Belum Bayar	test
2	kamar baru dan fresh	kasur,ac	2000000	002	2000000	kosong	\N	kamar baru
3	test	kasur	500000	003	500000	kosong	\N	kamar 3
\.


--
-- Data for Name: kebersihan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kebersihan (id, area_corridor, area_garden, area_parking, area_terrace, created_at, notes, room_number, updated_at) FROM stdin;
1	f	f	t	t	2025-10-29 16:31:20.574063	test	001	2025-11-04 16:40:56.014403
\.


--
-- Data for Name: otp_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.otp_tokens (id, email, expired_at, otp) FROM stdin;
\.


--
-- Data for Name: pembayaran; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pembayaran (id, bulan_bayar, catatan, created_at, kamar, kamar_id, nominal, penghuni, status, tahun_bayar, tanggal_bayar, tanggal_jatuh_tempo, updated_at, user_id) FROM stdin;
1	\N	\N	2025-11-04 17:23:12.821952	001	1	12000	geran	Lunas	\N	\N	2025-11-04 00:00:00	2025-11-04 17:23:12.821952	2
\.


--
-- Data for Name: pengumuman; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pengumuman (id, isi, judul, tanggal_berlaku) FROM stdin;
1	test	test	2025-10-29
\.


--
-- Data for Name: peraturan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.peraturan (id, deskripsi_peraturan, judul_peraturan) FROM stdin;
1	tttest	test
\.


--
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.profile (id, created_at, email, location, name, phone, profile_picture, room_number, status, user_id) FROM stdin;
\.


--
-- Data for Name: registration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.registration (id, email, enabled, password, phone_number, role, room_id, room_request_status, username) FROM stdin;
1	admin@kosapp.com	t	$2a$12$CS5sgFoTniOn0SrrV8mlp.Gx/3xu7a6xIH809678KSLcC54ZsR8ym	081234567890	ADMIN	\N	\N	admin
2	237006079@student.unsil.ac.id	t	$2a$10$1.TA3NN.VwIvWgXgpTi8QeZxTggxP5/B7KqUUH/wxQ8hx8O4bxDpW	098535281010	USER	1	APPROVED	geran
3	testuser123@example.com	t	$2a$10$hRYG4.IqQHolOmvgMx6/MO2yWtRtD4VOsik/4Rj8LyX5C5yD7/I3u	08123456789	USER	\N	\N	testuser123
5	arifin@gmail.com	t	$2a$10$vwvfxeP1ixxp1jlo/.XeFO8q9RS16n4NF1egxG/eVl6gVku0TmVZy	089567473849	USER	\N	\N	arifin
\.


--
-- Name: faq_admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.faq_admin_id_seq', 1, true);


--
-- Name: kamar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kamar_id_seq', 3, true);


--
-- Name: kebersihan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kebersihan_id_seq', 1, true);


--
-- Name: otp_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.otp_tokens_id_seq', 1, false);


--
-- Name: pembayaran_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pembayaran_id_seq', 1, true);


--
-- Name: pengumuman_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pengumuman_id_seq', 1, true);


--
-- Name: peraturan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.peraturan_id_seq', 1, true);


--
-- Name: profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.profile_id_seq', 1, false);


--
-- Name: registration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.registration_id_seq', 5, true);


--
-- Name: faq_admin faq_admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faq_admin
    ADD CONSTRAINT faq_admin_pkey PRIMARY KEY (id);


--
-- Name: kamar kamar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kamar
    ADD CONSTRAINT kamar_pkey PRIMARY KEY (id);


--
-- Name: kebersihan kebersihan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kebersihan
    ADD CONSTRAINT kebersihan_pkey PRIMARY KEY (id);


--
-- Name: otp_tokens otp_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.otp_tokens
    ADD CONSTRAINT otp_tokens_pkey PRIMARY KEY (id);


--
-- Name: pembayaran pembayaran_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pembayaran
    ADD CONSTRAINT pembayaran_pkey PRIMARY KEY (id);


--
-- Name: pengumuman pengumuman_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pengumuman
    ADD CONSTRAINT pengumuman_pkey PRIMARY KEY (id);


--
-- Name: peraturan peraturan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peraturan
    ADD CONSTRAINT peraturan_pkey PRIMARY KEY (id);


--
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- Name: registration registration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration
    ADD CONSTRAINT registration_pkey PRIMARY KEY (id);


--
-- Name: registration ukfw6boggmkktje4afntwpnqgul; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration
    ADD CONSTRAINT ukfw6boggmkktje4afntwpnqgul UNIQUE (username);


--
-- Name: kamar ukjx8vw2wyk3lflb2f8i9sqknk7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kamar
    ADD CONSTRAINT ukjx8vw2wyk3lflb2f8i9sqknk7 UNIQUE (nomor_kamar);


--
-- Name: registration ukpqp6404l2ndskpsr1xx8eaa68; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration
    ADD CONSTRAINT ukpqp6404l2ndskpsr1xx8eaa68 UNIQUE (email);


--
-- PostgreSQL database dump complete
--

