server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/railway
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 2

  jpa:
    hibernate:
      ddl-auto: update # Lebih aman daripada "update" untuk production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          schema-generation:
            database-action: none
